services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: madkunyah-server
    ports:
      - "5005:5005"
    environment:
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOST}
      PORT: ${PORT}
      CORS_ORIGIN: ${CORS_ORIGIN}
      COMMON_RATE_LIMIT_MAX_REQUESTS: ${COMMON_RATE_LIMIT_MAX_REQUESTS}
      COMMON_RATE_LIMIT_WINDOW_MS: ${COMMON_RATE_LIMIT_WINDOW_MS}
      DATABASE_URL: ${DATABASE_URL}
      MIDTRANS_SERVER_KEY: ${MIDTRANS_SERVER_KEY}
      MIDTRANS_CLIENT_KEY: ${MIDTRANS_CLIENT_KEY}
    restart: unless-stopped
